language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7

install:
  - composer self-update
  - composer update --prefer-source --no-interaction --ignore-platform-reqs

script:
  - php vendor/bin/phpunit
