# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    mangopay.client_id: "mangoPayClientId"
    mangopay.client_passphrase: "mangoPayClientPassPhrase"
    mangopay.base_url: "https://api.sandbox.mangopay.com/"
    mangopay.debug_mode: false

framework:
    secret: "symfonyFrameworkSecret"
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: mangopaySession
    profiler:
        collect: false
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: ['twig']

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
