parameters:
  #services class
  teknoo.mangopaybundle.service.mango_api.class: 'Teknoo\MangoPayBundle\Service\MangoApiService'
  teknoo.mangopaybundle.service.user.class: 'Teknoo\MangoPayBundle\Service\UserService'
  teknoo.mangopaybundle.service.session.class: 'Teknoo\MangoPayBundle\Service\SessionStorageService'
  teknoo.mangopaybundle.service.card_registration.class: 'Teknoo\MangoPayBundle\Service\CardRegistrationService'
  teknoo.mangopaybundle.service.secure_flow.class: 'Teknoo\MangoPayBundle\Service\SecureFlowService'

  #transcriber class
  teknoo.mangopaybundle.transcriber.user.class: 'Teknoo\MangoPayBundle\Transcriber\UserTranscriber'

  #storage strategy class
  teknoo.mangopaybundle.storage.local.class: 'Teknoo\MangoPayBundle\StorageStrategy\LocalStorage'

  #mangopay sdk class
  mangopay.sdk.mango_pay_api.class: 'MangoPay\MangoPayApi'
  mangopay.sdk.api_user.class: 'MangoPay\ApiUsers'
  mangopay.sdk.api_wallet.class: 'MangoPay\ApiWallets'
  mangopay.sdk.api_pay_ins.class: 'MangoPay\ApiPayIns'
  mangopay.sdk.api_pay_outs.class: 'MangoPay\ApiPayOuts'
  mangopay.sdk.api_transfert.class: 'MangoPay\ApiTransfers'
  mangopay.sdk.api_cards.class: 'MangoPay\ApiCards'
  mangopay.sdk.api_card_registrations.class: 'MangoPay\ApiCardRegistrations'
  mangopay.sdk.api_card_pre_authorizations.class: 'MangoPay\ApiCardPreAuthorizations'
  mangopay.sdk.api_refunds.class: 'MangoPay\ApiRefunds'
  mangopay.sdk.api_banking_aliases.class: 'MangoPay\ApiBankingAliases'
  mangopay.sdk.api_hooks.class: 'MangoPay\ApiHooks'
  mangopay.sdk.api_responses.class: 'MangoPay\ApiResponses'
  mangopay.sdk.api_kyc_documents.class: 'MangoPay\ApiKycDocuments'
  mangopay.sdk.api_clients.class: 'MangoPay\ApiClients'
  mangopay.sdk.api_events.class: 'MangoPay\ApiEvents'
  mangopay.sdk.api_disputes.class: 'MangoPay\ApiDisputes'
  mangopay.sdk.api_dispute_documents.class: 'MangoPay\ApiDisputeDocuments'
  mangopay.sdk.api_mandates.class: 'MangoPay\ApiMandates'
  mangopay.sdk.api_reports.class: 'MangoPay\ApiReports'

  #Parameters,
  #routes names for
  teknoo.mangopaybundle.parameters.card_registration.return.route: '_teknoo_mangopay_card_regitration_return'
  teknoo.mangopaybundle.parameters.secure_flow.return.route: '_teknoo_mangopay_secure_flow_return'

services:

  #mango pay sdk instance
  mangopay.sdk.mango_pay_api.service:
    class: "%mangopay.sdk.mango_pay_api.class%"
    calls:
      - [setHttpClient, ['@?mangopay.sdk.http_client']]
      - [setLogger, ['@?logger']]
    tags:
      - { name: monolog.logger, channel: mangopay }

  mangopay.sdk.api_user.service:
    class: "%mangopay.sdk.api_user.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiUsers']

  mangopay.sdk.api_wallet.service:
    class: "%mangopay.sdk.api_wallet.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiWallets']

  mangopay.sdk.api_pay_ins.service:
    class: "%mangopay.sdk.api_pay_ins.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiPayIns']

  mangopay.sdk.api_pay_outs.service:
    class: "%mangopay.sdk.api_pay_outs.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiPayOuts']

  mangopay.sdk.api_transfert.service:
    class: "%mangopay.sdk.api_transfert.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiTransferts']

  mangopay.sdk.api_cards.service:
    class: "%mangopay.sdk.api_cards.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiCards']

  mangopay.sdk.api_card_registrations.service:
    class: "%mangopay.sdk.api_card_registrations.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiCardRegistrations']

  mangopay.sdk.api_card_pre_authorizations.service:
    class: "%mangopay.sdk.api_card_pre_authorizations.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiCardPreAuthorizations']

  mangopay.sdk.api_refunds.service:
    class: "%mangopay.sdk.api_refunds.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiRefunds']

  mangopay.sdk.api_banking_aliases.service:
    class: "%mangopay.sdk.api_banking_aliases.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiBankingAliases']

  mangopay.sdk.api_hooks.service:
    class: "%mangopay.sdk.api_hooks.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiHooks']

  mangopay.sdk.api_responses.service:
    class: "%mangopay.sdk.api_responses.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiResponses']

  mangopay.sdk.api_kyc_documents.service:
    class: "%mangopay.sdk.api_kyc_documents.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiKycDocuments']

  mangopay.sdk.api_clients.service:
    class: "%mangopay.sdk.api_clients.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiClients']

  mangopay.sdk.api_disputes.service:
    class: "%mangopay.sdk.api_disputes.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiDisputes']

  mangopay.sdk.api_dispute_documents.service:
    class: "%mangopay.sdk.api_dispute_documents.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiDisputeDocuments']

  mangopay.sdk.api_mandates.service:
    class: "%mangopay.sdk.api_mandates.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiMandates']

  mangopay.sdk.api_reports.service:
    class: "%mangopay.sdk.api_reports.class%"
    factory: ['@teknoo.mangopaybundle.service.mango_api', 'getApiReports']

  #bundle services
  teknoo.mangopaybundle.transcriber.users:
    class: "%teknoo.mangopaybundle.transcriber.user.class%"

  teknoo.mangopaybundle.storage.local:
    class: "%teknoo.mangopaybundle.storage.local.class%"

  teknoo.mangopaybundle.service.session.storage:
    class: "%teknoo.mangopaybundle.service.session.class%"
    arguments:
      - '@session'

  teknoo.mangopaybundle.service.card_registration:
    class: "%teknoo.mangopaybundle.service.card_registration.class%"
    arguments:
      - '@mangopay.sdk.api_card_registrations.service'
      - '@router'
      - "%teknoo.mangopaybundle.parameters.card_registration.return.route%"
      - '@teknoo.mangopaybundle.service.session.storage'
      - '@event_dispatcher'

  teknoo.mangopaybundle.service.mango_api:
    class: "%teknoo.mangopaybundle.service.mango_api.class%"
    arguments:
      - '@mangopay.sdk.mango_pay_api.service'
      - "%mangopay.client_id%"
      - "%mangopay.client_passphrase%"
      - "%mangopay.base_url%"
      - "%mangopay.debug_mode%"
      - '@teknoo.mangopaybundle.storage.local'

  teknoo.mangopaybundle.service.user:
    class: "%teknoo.mangopaybundle.service.user.class%"
    arguments:
      - '@mangopay.sdk.api_user.service'
      - '@teknoo.mangopaybundle.transcriber.users'

  teknoo.mangopaybundle.service.secure_flow:
    class: "%teknoo.mangopaybundle.service.secure_flow.class%"
    arguments:
      - '@router'
      - "%teknoo.mangopaybundle.parameters.secure_flow.return.route%"
      - '@event_dispatcher'
      - '@mangopay.sdk.api_pay_ins.service'
      - '@teknoo.mangopaybundle.service.session.storage'
